### ISSUE TITLE
第一次测试就发现错误 吴:tun wu.是 shi ti

### ISSUE THREAD

**Issue by buffge** [Yurunsoft/PHPChineseToPinyin#1]
吴:tun wu.是 shi ti
我上网查了吴根本没有tun这个音,是也没有ti这个音

**Comment by Yurunsoft** [comment]
查了一下确实是的，这个词库也是网络上网友提供，有错误也是难免的，谢谢反馈！

**Comment by Yurunsoft** [comment]
原来的词库有问题，新的词库，更多中文和拼音相关功能的新类库，请移步：https://github.com/Yurunsoft/ChineseUtil
